### ISSUE TITLE
EnemyGeneratorの変更点

### ISSUE THREAD

**Issue by kobakoGlhf** [HIBIKI5201/Dungeon-Crafter#106]
作成するprefabををこちらから指定できるようにしてほしい。
またこちらからWaveDataを送るので、EnemySpawnDataのステータスに沿って連続して生成してほしい。
死亡時にWaveManagerのEnemyDeathCount()を呼んでほしい。

**Comment by HIBIKI5201** [comment]
Prefabの指定はEnumでやりましょう
辞書を作成し、Enumに対応したエネミーを生成するようにしましょう

**Comment by LengaTakamura** [comment]
辞書を作成し、Enumに対応したエネミーを生成するようにしましょう
作成済です　これからテストします
