### ISSUE TITLE
masterシーンのエネミーのバグ

### ISSUE THREAD

**Issue by Oriku0308** [HIBIKI5201/Dungeon-Crafter#168]
masterシーンでステージ1をプレイした際におこるバグ
エネミーが明らかに大量にスポーンする
エネミーが壁を無視して進む
　自分で設置した防衛設備は避けてすすむ

**Comment by LengaTakamura** [comment]
エネミーが明らかに大量にスポーンする
→PhaseDataがステージ０のものになっているのを確認しましたので直しておきます
エネミーが壁を無視して進む
→笠原君と協議します　今のところ何故かnavmeshObstacleをつけるとよける(よけ方が不自然)ことを確認しています

**Comment by Kasahara-Sota** [comment]
エネミーが壁を無視して進む
→壁にNavMeshObstacleをつけて、Curveにチェックを入れれば問題ないように見えます
