### ISSUE TITLE
不要なメンバー

### ISSUE THREAD

**Issue by HIBIKI5201** [HIBIKI5201/Dungeon-Crafter#39]
https://github.com/HIBIKI5201/Dungeon-Crafter/blob/23082823b701b0f7ab6e01e26fcb74ecee23c63c/Assets/Master/Script/InGame/Tallet/DefenseEquipmentManager_S/TrapTurretManager.cs#L13

このメンバー変数はローカルでもいいのでは

**Comment by NaritaShosei** [comment]
DrawCubeのところで使おうと思ってフィールド変数作ってたのにDrawCubeにSummonPositionをそのままいれてました

**Comment by HIBIKI5201** [comment]
デバッグ用のメンバーが必要な時は、メイン処理ではローカル変数を使って処理を済ませて、追加でメンバーに代入する処理を作るとデバッグ処理を消すときに問題起きにくいぞよ

**Comment by NaritaShosei** [comment]
なるほど、修正しときます

**Comment by NaritaShosei** [comment]
直しました
