### ISSUE TITLE
EnemyのベースクラスにRigidBodyを必須化

### ISSUE THREAD

**Issue by HIBIKI5201** [HIBIKI5201/Dungeon-Crafter#42]
https://github.com/HIBIKI5201/Dungeon-Crafter/blob/d3acf4a9520e87cbc9782da7511d56ba78c7a974/Assets/Master/Script/InGame/Enemy/EnemyManager_B.cs#L9
RequireComponentにRigidBodyを追加しといてください

当たり判定を持つ際に必要になります

**Comment by LengaTakamura** [comment]
対応しました
