### ISSUE TITLE
nullが出ます

### ISSUE THREAD

**Issue by NaritaShosei** [HIBIKI5201/Dungeon-Crafter#43]
https://github.com/HIBIKI5201/Dungeon-Crafter/blob/7fb5014fa98e4700967df4edffa7e278484f05c9/Assets/Master/Script/InGame/Enemy/EnemyManager_S/NormalEnemyManager.cs#L30

死んだときのメソッド(DeathBehaviour)でプールがなかった時にnullがでるので例外処理を作ってください

**Comment by LengaTakamura** [comment]
対応したので確認お願いします
