### ISSUE TITLE
ヘルスバーの更新処理

### ISSUE THREAD

**Issue by HIBIKI5201** [HIBIKI5201/Dungeon-Crafter#52]
エネミーマネージャーにヘルスバーマネージャーのインスタンスが渡されていない事で更新処理が行われていない

**Comment by HIBIKI5201** [comment]
はいその通りです
Managerのベースクラスではヘルスの更新が入るとHealthBarManagerに更新処理を行わせるようになっています
しかしHealthBarManagerがnullであるため更新が行われていません

**Comment by LengaTakamura** [comment]
これってエネミーマネージャーBクラスで参照せずにgeneratorで参照させてねってこと？それともエネミーマネージャーB書き換えて更新させるってこと？

**Comment by HIBIKI5201** [comment]
Managerが各自のHealthBarを管理する方が適切でしょう

**Comment by LengaTakamura** [comment]
了解しました

**Comment by LengaTakamura** [comment]
このmanagerってgeneratorのほうですよね？

**Comment by LengaTakamura** [comment]
解決したので確認お願いします
そもそもインスタンスがGeneratorに渡されていなかったことと、EnemyHealthBarManagerが不適切な位置にアタッチされていたことが原因でした
