### ISSUE TITLE
UnassignedReferenceExceptionが出力される

### ISSUE THREAD

**Issue by NaritaShosei** [HIBIKI5201/Dungeon-Crafter#65]
https://github.com/HIBIKI5201/Dungeon-Crafter/blob/93ca0e02aa6ce0ae7f987fb096753f875cfa60f9/Assets/Dev/Dev_Branchs/enemy/Test_EnemyGenerator.cs#L63

UnassignedReferenceExceptionが出力されて実行できないので対応お願いします

**Comment by LengaTakamura** [comment]
確認しましたが同じようなエラーはこちらでは出ていないのでヘルスバーとキャンバスが二つアサインされているか再度確認お願いします

**Comment by NaritaShosei** [comment]
アサインしていなかったのですが、何をアサインすればいいのかわかりにくいのでデバッグ用にプレハブを作成してくれると助かります。

**Comment by LengaTakamura** [comment]
わかりました

**Comment by LengaTakamura** [comment]
canvasのprefabはMaster→Prefab→InGame→InGameSystemプレハブに含まれています
HealthBarのprefabはMaster→Prefab→InGame→Enemy→HealthBarプレハブです

**Comment by NaritaShosei** [comment]
解決しました、ありがとうございます。
ですが、TargetPosにてエラーが出力されるのですが、TargetPosにはなにをアサインすればよいですか？

**Comment by LengaTakamura** [comment]
targetPosには目的地に設定したい座標に空のオブジェクトを作ってそのオブジェクトをアサインしてください

**Comment by NaritaShosei** [comment]
目的地はNavMeshのSetDestinationで設定する目的地、のようなニュアンスで受け取っていい感じですか？

**Comment by LengaTakamura** [comment]
そうです

**Comment by NaritaShosei** [comment]
わかりました、もう夜も遅いので明日確認してみます。
ありがとうございました。

**Comment by NaritaShosei** [comment]
解決しました。ありがとうございました。

**Comment by HIBIKI5201** [comment]
再度

**Comment by HIBIKI5201** [comment]
再発の危険性があるので、EnemyGeneratorのプレハブにアサインを完了させた状態出作って下さい
今後はそれを使用します

**Comment by LengaTakamura** [comment]
アサインされた状態のものをstragemanagerプレハブに組み込みました
