### ISSUE TITLE
StageManagerのTransformフィールドについて

### ISSUE THREAD

**Issue by HIBIKI5201** [HIBIKI5201/Dungeon-Crafter#79]
_startPos、_targetPosをStageManagerが持つのは不健全です
何故ならEnemyGeneratorとStageManagerで違うオブジェクトがアサインされた場合にバグが発生し、これを発見するのが難しいからです
よってEnemyGeneratorのTransformフィールドにプロパティを追加し、StageManagerはそれを参照する形にしてください
人為的エラーがゲーム開発にとって最も警戒するべきものである事に注意してください

**Comment by LengaTakamura** [comment]
プロパティを作成し参照する形にしました
