### ISSUE TITLE
StageをProBuilderにした際の問題

### ISSUE THREAD

**Issue by HIBIKI5201** [HIBIKI5201/Dungeon-Crafter#90]
- [x] Enemyが移動しなくなる
- [x] 施設の設置ができない
- [x] マテリアルがズレている

**Comment by kobakoGlhf** [comment]
ノードがうまく繋がってなかったので修正します。

**Comment by HIBIKI5201** [comment]
@kobakoGlhf 
問題が起きているのはStageブランチなので、StageブランチからGraphicブランチに直接マージして作業してください

**Comment by kobakoGlhf** [comment]
とりあえず修正したのですが、マージして作業ってどういうこと？

**Comment by kobakoGlhf** [comment]
unityの内部にあるオブジェクトについては問題なく実装できそうなのですが、probuilderのUVに問題がありそうです。
この状態で端を基準にタイリングすることは難しそうです。

**Comment by HIBIKI5201** [comment]
@kobakoGlhf 
StageManagerのようにTransformのScaleから計算する事はできませんか？
ScaleからTilling Scaleを割った余りだけ座標をズラす事ができれば対処出来るかもしれません

**Comment by kobakoGlhf** [comment]
解決しました。

**Comment by HIBIKI5201** [comment]
解決
